### ISSUE TITLE
Paper Candidates

### ISSUE THREAD

**Issue by meneguzzi** [lsa-pucrs/asg-meetings#4]
Selecionei uns artigos do AI Journal, gostaria que vocês votassem nisto:

- [An extension of metric temporal planning with application to AC voltage control](http://www.sciencedirect.com/science/article/pii/S0004370215001332)
- [Automatic construction of optimal static sequential portfolios for AI planning and beyond](http://www.sciencedirect.com/science/article/pii/S000437021500079X)
- [Transferring knowledge as heuristics in reinforcement learning: A case-based approach](http://www.sciencedirect.com/science/article/pii/S000437021500082X)
- [Relevance in belief revision](http://www.sciencedirect.com/science/article/pii/S0004370215001228)

Estou aberto para outras artigos daqui:
[Artificial Intelligence](http://www.sciencedirect.com/science/journal/00043702)

**Comment by meneguzzi** [comment]
@anibalsolon @ramonpereira @rafaelcaue @stchepanhagn @Maumagnaguagno @leonardoamado 
@JoaoPauloAires 
Algum de vocês tem opinião sobre estes artigos?

**Comment by ramonpereira** [comment]
Meu voto: An extension of metric temporal planning with application to AC voltage control.

**Comment by rafaelcaue** [comment]
Eu voto no Relevance in belief revision

**Comment by anibalsolon** [comment]
Também fico com Relevance in belief revision

**Comment by stchepanhagn** [comment]
Relevance in belief revision.

**Comment by leonardoamado** [comment]
Relevance in belief revision.

**Comment by JoaoPauloAires** [comment]
Vou nesse: Transferring knowledge as heuristics in reinforcement learning: A case-based approach

**Comment by Maumagnaguagno** [comment]
Transferring knowledge as heuristics in reinforcement learning

**Comment by meneguzzi** [comment]
Acho que podemos colocar todos, mas espaçados com artigos de conferências (como o que me enviaram), mas vou usar os votos de vocês para priorizar então.

Valeu a participação!
