### ISSUE TITLE
Deep Neural Networks and NLP

### ISSUE THREAD

**Issue by JoaoPauloAires** [lsa-pucrs/asg-meetings#5]
http://www.nlpr.ia.ac.cn/cip/ZongPublications/2015/IEEE-Zhang-8-5.pdf

Que tal?

**Comment by anibalsolon** [comment]
Apoio :) Tem alguns conceitos mais complexos, mas no todo é tranquilo.
Cita até HMM para deixar o @stchepanhagn feliz!

**Comment by rafaelcaue** [comment]
Parece tri, não conheço o assunto mas é melhor que o de 32 paginas!

**Comment by meneguzzi** [comment]
Buenas, atendendo a pedidos, fiz a troca do artigo.
