### ISSUE TITLE
Paper candidates pre-second journal paper

### ISSUE THREAD

**Issue by meneguzzi** [lsa-pucrs/asg-meetings#6]
[Admissible Landmark Heuristic for Multi-Agent Planning](https://www.aaai.org/ocs/index.php/ICAPS/ICAPS15/paper/view/10608) - Michal Štolba, Daniel Fišer, Antonín Komenda

[Tight Bounds for HTN Planning](http://www.aaai.org/ocs/index.php/ICAPS/ICAPS15/paper/view/10611) - Ron Alford, Pascal Bercher, David W. Aha

[Sequencing Operator Counts](http://www.aaai.org/ocs/index.php/ICAPS/ICAPS15/paper/view/10618) - Toby O. Davies, Adrian R. Pearce, Peter J. Stuckey, Nir Lipovetzky

**Comment by meneguzzi** [comment]
@anibalsolon @ramonpereira @rafaelcaue @stchepanhagn @Maumagnaguagno @leonardoamado 
@JoaoPauloAires 

Novamente, votem nisto para eu poder pontuar os artigos extensos com artigos deste tipo.

**Comment by rafaelcaue** [comment]
Esse foi fácil para mim, meu voto é Admissible Landmark Heuristic for Multi-Agent Planning :)

**Comment by anibalsolon** [comment]
Tem voto nulo? :sweat:

**Comment by JoaoPauloAires** [comment]
Eu vou nulo nesse.

**Comment by meneguzzi** [comment]
Open your minds!

**Comment by Maumagnaguagno** [comment]
Estou na dúvida entre dois, preferência nessa ordem:
1. Tight Bounds for HTN Planning
2. Sequencing Operator Counts

**Comment by ramonpereira** [comment]
Vou nesse: Sequencing Operator Counts

**Comment by meneguzzi** [comment]
Coloquei um deles na lista, vou deixar os demais aqui para referência futura. Espero sugestões de papers não de planning para adicionar lá.
