### ISSUE TITLE
Rendering Conferences Top Down

### ISSUE THREAD

**Issue by meneguzzi** [lsa-pucrs/asg-meetings#7]
Graphviz is not rendering the graph top down as I expected. @Maumagnaguagno,  can you check what I'm doing wrong?

**Comment by Maumagnaguagno** [comment]
Graphviz considers each sequence ``a -> b -> c`` as one top down graph and display each graph side-by-side. Without a connection between ``c`` and ``d`` nodes there is no top down constraint.
I enforced such constraints with invisible month nodes in the LR version.
I also updated the LR version with SAC.

**Comment by Maumagnaguagno** [comment]
I am adding an automatic generator based on Markdown files, it will be easier to maintain.

**Comment by meneguzzi** [comment]
Thanks Mauricio
