### ISSUE TITLE
Add FLAIRS dates

### ISSUE THREAD

**Issue by meneguzzi** [lsa-pucrs/asg-meetings#8]
[http://www.flairs-30.info](http://www.flairs-30.info) - Deadline November. Check previous years to make sure the deadline is consistent.

**Comment by Maumagnaguagno** [comment]
FLAIRS deadline is consistent based on current and last two events: [FLAIRS 30](http://www.flairs-30.info/), [FLAIRS 29](http://www.flairs-29.info/) and [FLAIRS 28](https://sites.google.com/a/boonthum-denecke.com/flairs-28/dates).
- November (Paper submission deadline)
- January (Paper acceptance notification)
- February (Camera ready version due)

I suppose you want this event in the conferences.md file and the timeline PDF generated from it.
